on: 
  push: 
    branches:
      - main
env:
  DOCKER_IMAGE_NAME: boxlang-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup vars
        id: vars
        run: |
          lcased=$(echo "${{ github.repository }}" | tr "[:upper:]" "[:lower:]")

          echo "repository_lower=$lcased" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master   

      - name: Github Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: publisher
          password: ${{ secrets.GITHUB_TOKEN }}    

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          # Disabling provenance check due to https://community.fly.io/t/images-built-with-the-latest-docker-buildx-and-or-github-actions-work-again/10816
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          file: .github/build/Dockerfile
          context: .
          tags: |
            ghcr.io/${{ steps.vars.outputs.repository_lower }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          push: true